const U='https://kpotsnjhysgrhlnlhdnz.supabase.co';
const K='sb_publishable_DghWWFFdMmpY84PlZG7lMw_a0mKXqeX';
const HEAD={apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json'};
const S={members:[],goals:[],checkins:[],settings:{},quotes:[],ledger:[],settlements:[],memberId:localStorage.getItem('ilshinhoe_member')||'son-jeongwoo'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function ds(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function mon(d=new Date()){d=new Date(d);d.setDate(d.getDate()-((d.getDay()+6)%7));d.setHours(0,0,0,0);return d}
function addDays(d,n){d=new Date(d);d.setDate(d.getDate()+n);return d}
function money(n){return new Intl.NumberFormat('ko-KR').format(Number(n)||0)+'원'}
function member(id){return S.members.find(m=>m.id===id)}
function memberGoals(id){return S.goals.filter(g=>g.member_id===id&&g.active)}
function goalCheckins(id){return S.checkins.filter(c=>c.goal_id===id)}
function thisWeekCheckins(id){const a=ds(mon()),b=ds(addDays(mon(),6));return S.checkins.filter(c=>c.goal_id===id&&c.check_date>=a&&c.check_date<=b)}
function weekXP(id){return memberGoals(id).reduce((x,g)=>{const n=thisWeekCheckins(g.id).length;return x+n*20+(g.cadence==='weekly'&&n>=g.target_count?40:0)},0)}
function totalXP(id){return memberGoals(id).reduce((x,g)=>x+goalCheckins(g.id).length*20,0)}
function levelInfo(xp){const level=Math.floor(xp/120)+1;const titles=['INITIATE','RUNNER','EXECUTOR','VANGUARD','CHAIR'];return {level,title:titles[Math.min(titles.length-1,level-1)],pct:Math.round((xp%120)/120*100)}}
function streak(id){const dates=[...new Set(memberGoals(id).flatMap(g=>goalCheckins(g.id).map(c=>c.check_date)))].sort().reverse();if(!dates.length)return 0;let d=new Date();if(dates[0]!==ds(d)){d.setDate(d.getDate()-1);if(dates[0]!==ds(d))return 0}let s=0;for(const v of dates){if(v===ds(d)){s++;d.setDate(d.getDate()-1)}else break}return s}
function currentRisk(id){const now=new Date(),elapsed=((now.getDay()+6)%7)+1,a=ds(mon()),b=ds(now);let total=0;for(const g of memberGoals(id)){if(g.cadence==='daily'){const n=S.checkins.filter(c=>c.goal_id===g.id&&c.check_date>=a&&c.check_date<=b).length;total+=Math.max(0,elapsed-n)*g.fine_amount}else{const n=thisWeekCheckins(g.id).length;if(now.getDay()===0&&n<g.target_count)total+=g.fine_amount}}return total}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1500)}
async function api(path,opt={}){const r=await fetch(`${U}/rest/v1/${path}`,{...opt,headers:{...HEAD,...(opt.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t||r.statusText);return t?JSON.parse(t):null}
async function rpc(name,body){return api(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}

function quoteForToday(){if(!S.quotes.length)return null;const d=new Date();const seed=Number(`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`);return S.quotes[seed%S.quotes.length]}
function renderQuote(){const q=quoteForToday();$('#dailyQuote').textContent=q?.quote_text||'오늘 할 일을 오늘 끝낸다.';$('#quoteBy').textContent=q?.attribution||'일신회'}
function renderRanking(){const rows=[...S.members].sort((a,b)=>weekXP(b.id)-weekXP(a.id));$('#ranking').innerHTML=rows.map((m,i)=>{const li=levelInfo(totalXP(m.id));return `<div class="rank-row"><div class="rank-no">${String(i+1).padStart(2,'0')}</div><div class="avatar">${m.display_name[0]}</div><div class="rank-main"><b>${m.display_name}</b><small>LV.${li.level} ${li.title} · ${streak(m.id)}일 연속</small></div><div class="xp">${weekXP(m.id)} XP</div></div>`}).join('')}
function renderTabs(){if(!member(S.memberId)&&S.members[0])S.memberId=S.members[0].id;$('#memberTabs').innerHTML=S.members.map(m=>{const li=levelInfo(totalXP(m.id));return `<button class="member-tab ${m.id===S.memberId?'active':''}" data-member="${m.id}"><div class="avatar">${m.display_name[0]}</div><div><b>${m.display_name}</b><small>LV.${li.level} · ${memberGoals(m.id).length} OATHS</small></div></button>`}).join('');$$('[data-member]').forEach(b=>b.onclick=()=>{S.memberId=b.dataset.member;localStorage.setItem('ilshinhoe_member',S.memberId);render();updateBadge()})}
function renderProfile(){const m=member(S.memberId);if(!m)return;const xp=totalXP(m.id),li=levelInfo(xp);$('#profile').innerHTML=`<div class="profile-head"><div class="avatar">${m.display_name[0]}</div><div class="profile-name"><h3>${m.display_name}</h3><p>ILSHINHOE MEMBER · ${li.title}</p></div><div class="level-badge">LV.${li.level}</div></div><div class="progress"><i style="width:${li.pct}%"></i></div><div class="profile-minis"><div><b>${streak(m.id)}일</b><span>연속 기록</span></div><div><b>${weekXP(m.id)} XP</b><span>주간 경험치</span></div><div><b>${money(currentRisk(m.id)).replace('원','')}</b><span>예상 벌금</span></div></div>`}
function progress(g){return g.cadence==='daily'?(S.checkins.some(c=>c.goal_id===g.id&&c.check_date===ds())?1:0):thisWeekCheckins(g.id).length}
function renderGoals(){const gl=memberGoals(S.memberId);$('#goalCount').textContent=`${gl.length}개 활성`;$('#goals').innerHTML=gl.length?gl.map((g,i)=>{const p=progress(g),target=g.cadence==='daily'?1:g.target_count,done=p>=target;return `<article class="goal-card panel"><div class="goal-top"><div class="goal-index"><span>${i+1}</span></div><div class="goal-main"><div class="goal-title">${escapeHtml(g.title)}<span class="tag">${g.cadence==='daily'?'DAILY':'WEEKLY '+g.target_count}</span></div><div class="goal-desc">${escapeHtml(g.description||'세부 내용 없음')}${g.proof_method?`<br>인증 · ${escapeHtml(g.proof_method)}`:''}</div></div><div class="goal-fine">-${money(g.fine_amount)}</div></div><div class="goal-progress"><div class="progress"><i style="width:${Math.min(100,p/target*100)}%"></i></div><small>${p}/${target}</small></div><div class="goal-actions"><button class="check-btn ${done?'done':''}" data-check="${g.id}">${done&&g.cadence==='daily'?'✓ 오늘 완료':g.cadence==='daily'?'오늘 완료 체크':'+ 1회 기록'}</button><button class="edit-btn" data-edit="${g.id}" aria-label="서약 수정">⋯</button></div></article>`}).join(''):'<div class="panel ledger-empty">아직 서약이 없습니다. 첫 서약을 추가하세요.</div>';$$('[data-check]').forEach(b=>b.onclick=()=>toggleCheck(b.dataset.check));$$('[data-edit]').forEach(b=>b.onclick=()=>openGoal(S.goals.find(g=>g.id===b.dataset.edit)))}
function renderLedger(){const rows=S.ledger.filter(f=>f.member_id===S.memberId);const open=rows.filter(f=>f.status==='open').reduce((a,b)=>a+b.total_amount,0);$('#ledgerSummary').textContent=open?`미정산 ${money(open)}`:'미정산 없음';$('#ledger').innerHTML=rows.length?rows.slice(0,12).map(f=>`<div class="ledger-row"><div><b>${escapeHtml(f.goal_title)}</b><small>${f.week_start} 주차 · ${escapeHtml(f.reason)} · ${f.status==='settled'?'정산 완료':f.status==='waived'?'면제':'미정산'}</small></div><div class="ledger-amount"><strong class="${f.status==='settled'?'settled':''}">${money(f.total_amount)}</strong>${f.status==='open'?`<button class="settle-btn" data-settle="${f.id}">정산 완료</button>`:''}</div></div>`).join(''):'<div class="ledger-empty">확정된 벌금이 없습니다.<br>완료된 주차는 자동으로 원장에 고정됩니다.</div>';$$('[data-settle]').forEach(b=>b.onclick=()=>settleFine(b.dataset.settle))}
function render(){const a=ds(mon()),b=ds(addDays(mon(),6));$('#dateLabel').textContent=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date());$('#weekCheckins').textContent=S.checkins.filter(c=>c.check_date>=a&&c.check_date<=b).length;$('#activeGoals').textContent=S.goals.filter(g=>g.active).length;$('#riskFine').textContent=money(S.members.reduce((x,m)=>x+currentRisk(m.id),0)).replace('원','');renderQuote();renderRanking();renderTabs();renderProfile();renderGoals();renderLedger();$('#rules').textContent=S.settings.group_rules||'매주 일요일이 끝난 뒤 주간 정산\n미달성 시 서약별 설정 벌금 적용';}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

async function toggleCheck(goalId){const g=S.goals.find(x=>x.id===goalId),existing=S.checkins.find(c=>c.goal_id===goalId&&c.check_date===ds());try{if(existing&&g.cadence==='daily'){if(!confirm('오늘 완료 기록을 취소할까요? 변경 이력은 서버 감사 로그에 남습니다.'))return;await api(`goal_checkins?id=eq.${existing.id}`,{method:'DELETE'});toast('오늘 기록 취소')}else if(existing){toast('오늘 기록은 이미 있습니다');return}else{await api('goal_checkins',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({goal_id:goalId,check_date:ds(),note:''})});toast('+20 XP')}await load()}catch(e){console.error(e);toast('저장 실패')}}
async function settleFine(id){if(!confirm('이 벌금을 정산 완료로 표시할까요? 금액과 원장 내용은 변경되지 않습니다.'))return;try{await api(`fine_ledger?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'settled'})});toast('정산 완료');await load()}catch(e){console.error(e);toast('정산 저장 실패')}}
function openGoal(g=null){$('#goalForm').reset();$('#goalId').value=g?.id||'';$('#dialogTitle').textContent=g?'서약 수정':'새 서약';$('#goalTitle').value=g?.title||'';$('#goalDescription').value=g?.description||'';$('#goalProof').value=g?.proof_method||'';$('#goalCadence').value=g?.cadence||'daily';$('#goalTarget').value=g?.target_count||1;$('#goalFine').value=g?.fine_amount??10000;$('#deleteGoalBtn').hidden=!g;syncCadence();$('#goalDialog').showModal()}
function syncCadence(){const weekly=$('#goalCadence').value==='weekly';$('#goalTarget').disabled=!weekly;if(!weekly)$('#goalTarget').value=1}
async function saveGoal(e){e.preventDefault();const id=$('#goalId').value,p={member_id:S.memberId,title:$('#goalTitle').value.trim(),description:$('#goalDescription').value.trim(),proof_method:$('#goalProof').value.trim(),cadence:$('#goalCadence').value,target_count:Number($('#goalTarget').value)||1,fine_amount:Number($('#goalFine').value)||0,active:true};if(!p.title)return;try{await api(id?`goals?id=eq.${id}`:'goals',{method:id?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(p)});$('#goalDialog').close();toast(id?'서약 수정 완료':'서약 추가 완료');await load()}catch(e2){console.error(e2);toast('서약 저장 실패')}}
async function deleteGoal(){const id=$('#goalId').value;if(!id||!confirm('이 서약을 삭제할까요? 과거 체크·벌금 이력은 감사 로그와 원장에 보존됩니다.'))return;try{await api(`goals?id=eq.${id}`,{method:'DELETE'});$('#goalDialog').close();toast('서약 삭제');await load()}catch(e){console.error(e);toast('삭제 실패')}}
async function finalizeMissingWeeks(){if(!S.goals.length)return;const completed=addDays(mon(),-7);let first=mon(new Date(Math.min(...S.goals.map(g=>new Date(g.created_at).getTime()))));const known=new Set(S.settlements.map(x=>x.week_start));let count=0;while(first<=completed&&count<60){const w=ds(first);if(!known.has(w)){try{await rpc('finalize_week',{p_week_start:w})}catch(e){console.error('finalize_week',w,e)}}first=addDays(first,7);count++}}
async function updateBadge(){if(!('setAppBadge' in navigator))return;const pending=memberGoals(S.memberId).filter(g=>g.cadence==='daily'&&!S.checkins.some(c=>c.goal_id===g.id&&c.check_date===ds())).length;try{pending?await navigator.setAppBadge(pending):await navigator.clearAppBadge()}catch{}}
async function exportBackup(){try{const payload={exported_at:new Date().toISOString(),group:'ILSHINHOE',members:S.members,goals:S.goals,goal_checkins:S.checkins,fine_ledger:S.ledger,settings:S.settings,settlements:S.settlements};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ilshinhoe-backup-${ds()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('백업 파일 생성')}catch(e){console.error(e);toast('백업 실패')}}
async function load(){const sync=$('#syncState');sync.textContent='서버 동기화 중';sync.classList.remove('error');try{const start=ds(addDays(new Date(),-365));const [members,goals,checkins,settings,quotes,ledger,settlements]=await Promise.all([api('members?select=*&order=created_at.asc'),api('goals?select=*&order=sort_order.asc,created_at.asc'),api(`goal_checkins?select=*&check_date=gte.${start}&order=check_date.desc`),api('settings?select=*'),api('quotes?select=*&active=eq.true&order=id.asc'),api('fine_ledger?select=*&order=week_start.desc,created_at.desc'),api('weekly_settlements?select=*&order=week_start.desc')]);Object.assign(S,{members:members||[],goals:goals||[],checkins:checkins||[],quotes:quotes||[],ledger:ledger||[],settlements:settlements||[],settings:Object.fromEntries((settings||[]).map(x=>[x.key,x.value]))});render();await finalizeMissingWeeks();sync.textContent='서버 동기화 완료';await updateBadge()}catch(e){console.error(e);sync.textContent='연결 오류';sync.classList.add('error');toast('서버 연결 오류')}}

let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});window.addEventListener('appinstalled',()=>{$('#installBtn').hidden=true;installPrompt=null;toast('일신회 앱 설치 완료')});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true}else{toast('Chrome 메뉴에서 앱 설치를 선택하세요')}};
$('#addGoalBtn').onclick=()=>openGoal();$('#goalCadence').onchange=syncCadence;$('#goalForm').addEventListener('submit',saveGoal);$('#deleteGoalBtn').onclick=deleteGoal;$('#exportBtn').onclick=exportBackup;
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
load();setInterval(load,60000);
