const U='https://kpotsnjhysgrhlnlhdnz.supabase.co';
const K='sb_publishable_DghWWFFdMmpY84PlZG7lMw_a0mKXqeX';
const H={apikey:K,Authorization:'Bearer '+K,'Content-Type':'application/json'};
const LAST_KEY='ilshinhoe_last_member';
const MINE_KEY='ilshinhoe_my_member';
const legacy=localStorage.getItem('ilshinhoe_member');
const S={members:[],goals:[],checks:[],quotes:[],ledger:[],settings:{},memberId:localStorage.getItem(LAST_KEY)||legacy||localStorage.getItem(MINE_KEY)||'son-jeongwoo',myMemberId:localStorage.getItem(MINE_KEY)||''};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const ds=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function monday(d=new Date()){d=new Date(d);d.setDate(d.getDate()-((d.getDay()+6)%7));d.setHours(0,0,0,0);return d}
function addDays(d,n){d=new Date(d);d.setDate(d.getDate()+n);return d}
const money=n=>new Intl.NumberFormat('ko-KR').format(Number(n)||0)+'원';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){const r=await fetch(`${U}/rest/v1/${path}`,{...opt,headers:{...H,...(opt.headers||{})}});const t=await r.text();if(!r.ok)throw Error(t||r.statusText);return t?JSON.parse(t):null}
function member(id){return S.members.find(x=>x.id===id)}
function memberGoals(id,activeOnly=true){return S.goals.filter(g=>g.member_id===id&&(!activeOnly||g.active))}
function weekChecks(id){const a=ds(monday()),b=ds(addDays(monday(),6));return S.checks.filter(c=>c.goal_id===id&&c.check_date>=a&&c.check_date<=b)}
function todayDone(g){return S.checks.some(c=>c.goal_id===g.id&&c.check_date===ds())}
function weekXP(id){return memberGoals(id).reduce((sum,g)=>{const n=weekChecks(g.id).length;return sum+n*20+(g.cadence==='weekly'&&n>=g.target_count?40:0)},0)}
function totalXP(id){const ids=new Set(memberGoals(id,false).map(g=>g.id));return S.checks.filter(c=>ids.has(c.goal_id)).length*20}
function level(x){return Math.floor(x/120)+1}
function streak(id){const ids=new Set(memberGoals(id,false).map(g=>g.id));const dates=[...new Set(S.checks.filter(c=>ids.has(c.goal_id)).map(c=>c.check_date))].sort().reverse();if(!dates.length)return 0;let d=new Date();if(dates[0]!==ds(d)){d.setDate(d.getDate()-1);if(dates[0]!==ds(d))return 0}let s=0;for(const v of dates){if(v===ds(d)){s++;d.setDate(d.getDate()-1)}else break}return s}
function risk(id){const now=new Date(),start=ds(monday()),end=ds(now),elapsed=((now.getDay()+6)%7)+1;let sum=0;for(const g of memberGoals(id)){if(g.cadence==='daily'){const n=S.checks.filter(c=>c.goal_id===g.id&&c.check_date>=start&&c.check_date<=end).length;sum+=Math.max(0,elapsed-n)*Number(g.fine_amount||0)}else if(now.getDay()===0&&weekChecks(g.id).length<g.target_count){sum+=Number(g.fine_amount||0)}}return sum}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1500)}
function quoteToday(){if(!S.quotes.length)return null;const d=new Date(),seed=Number(`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`);return S.quotes[seed%S.quotes.length]}
function chooseMember(id){if(!member(id))return;S.memberId=id;localStorage.setItem(LAST_KEY,id);localStorage.setItem('ilshinhoe_member',id);render();badge()}
function pinMember(id){if(!member(id))return;S.myMemberId=id;localStorage.setItem(MINE_KEY,id);localStorage.setItem(LAST_KEY,id);localStorage.setItem('ilshinhoe_member',id);S.memberId=id;render();toast(`${member(id).display_name}을 내 프로필로 고정했어요`);badge()}
function renderSwitcher(){if(!member(S.memberId)&&S.members[0]){S.memberId=S.members[0].id;localStorage.setItem(LAST_KEY,S.memberId)}$('#switcher').innerHTML=S.members.map(m=>`<button class="member-btn ${m.id===S.memberId?'active':''} ${m.id===S.myMemberId?'mine':''}" data-member="${esc(m.id)}" type="button"><span class="initial">${esc(m.display_name[0])}</span><span class="name">${esc(m.display_name)}</span></button>`).join('');$$('[data-member]').forEach(b=>{let timer=null,longHit=false;const cancel=()=>{if(timer){clearTimeout(timer);timer=null}};b.addEventListener('pointerdown',()=>{longHit=false;timer=setTimeout(()=>{longHit=true;pinMember(b.dataset.member)},650)});b.addEventListener('pointerup',cancel);b.addEventListener('pointerleave',cancel);b.addEventListener('pointercancel',cancel);b.addEventListener('click',()=>{if(longHit){longHit=false;return}chooseMember(b.dataset.member)});b.addEventListener('contextmenu',e=>e.preventDefault())})}
function renderStatus(){const gs=memberGoals(S.memberId),activeIds=new Set(gs.map(g=>g.id)),doneToday=new Set(S.checks.filter(c=>activeIds.has(c.goal_id)&&c.check_date===ds()).map(c=>c.goal_id)).size;$('#statusStrip').innerHTML=`<div class="stat"><b>${doneToday}/${gs.length}</b><span>오늘 체크</span></div><div class="stat"><b>${weekXP(S.memberId)}</b><span>이번 주 XP</span></div><div class="stat"><b>${money(risk(S.memberId)).replace('원','')}</b><span>예상 벌금</span></div>`}
function renderGoals(){const gs=memberGoals(S.memberId);$('#goalCount').textContent=`${gs.length}개`;$('#goals').className=gs.length?'todo-list':'';$('#goals').innerHTML=gs.length?gs.map(g=>{const daily=g.cadence==='daily',n=daily?(todayDone(g)?1:0):weekChecks(g.id).length,target=daily?1:Number(g.target_count||1),pct=Math.min(100,n/target*100),doneTodayFlag=todayDone(g),detail=g.description||g.proof_method||'체크해서 기록';return `<article class="todo"><div class="todo-main" data-edit="${g.id}"><div class="todo-title"><b>${esc(g.title)}</b><span class="cadence">${daily?'매일':'주 '+target+'회'}</span></div><div class="todo-meta">${esc(detail)} <span class="fine">· ${money(g.fine_amount)} 벌금</span></div>${daily?'':`<div class="todo-progress"><i style="width:${pct}%"></i></div>`}</div><button class="check-btn ${daily?'':'weekly'} ${doneTodayFlag?'done':''}" data-check="${g.id}" type="button">${daily?(doneTodayFlag?'✓':'○'):(doneTodayFlag?'✓':'+')}</button></article>`}).join(''):'<div class="empty">할 일이 없어요.<br>오른쪽 위 ‘추가’에서 만들 수 있어요.</div>';$$('[data-check]').forEach(b=>b.onclick=()=>toggleCheck(b.dataset.check));$$('[data-edit]').forEach(b=>b.onclick=()=>openGoal(S.goals.find(g=>g.id===b.dataset.edit)))}
function renderRanking(){const rows=[...S.members].sort((a,b)=>weekXP(b.id)-weekXP(a.id));$('#ranking').innerHTML=rows.map((m,i)=>`<div class="rank-row"><div class="rank-no">${i+1}</div><div class="rank-avatar">${esc(m.display_name[0])}</div><div class="rank-info"><b>${esc(m.display_name)}</b><span>LV.${level(totalXP(m.id))} · ${streak(m.id)}일 연속</span></div><div class="rank-xp"><b>${weekXP(m.id)}</b><span>XP</span></div></div>`).join('')}
function renderLedger(){const rows=S.ledger.filter(x=>x.member_id===S.memberId),open=rows.filter(x=>x.status==='open').reduce((s,x)=>s+Number(x.total_amount),0);$('#ledgerSummary').innerHTML=`<span>${esc(member(S.memberId)?.display_name||'')} 미정산</span><b>${money(open)}</b>`;$('#ledger').className=rows.length?'list-card ledger-card':'';$('#ledger').innerHTML=rows.length?rows.slice(0,30).map(x=>`<div class="ledger-row"><div class="ledger-main"><b>${esc(x.goal_title)}</b><span>${x.week_start} · ${esc(x.reason)} · ${x.status==='settled'?'정산 완료':'미정산'}</span></div><div class="ledger-money"><b class="${x.status==='settled'?'settled':''}">${money(x.total_amount)}</b>${x.status==='open'?`<button class="settle" data-settle="${x.id}" type="button">정산 완료</button>`:''}</div></div>`).join(''):'<div class="empty">확정된 벌금이 없어요.</div>';$$('[data-settle]').forEach(b=>b.onclick=()=>settle(b.dataset.settle))}
function render(){const m=member(S.memberId);if(!m)return;const d=new Date(),q=quoteToday(),start=monday();$('#dateLabel').textContent=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(d);$('#helloName').textContent=m.display_name;$('#levelBadge').textContent=`LV.${level(totalXP(m.id))}`;$('#weekLabel').textContent=`${start.getMonth()+1}.${start.getDate()} – ${addDays(start,6).getMonth()+1}.${addDays(start,6).getDate()}`;$('#quoteText').textContent=q?.quote_text||'오늘 할 일을 오늘 끝낸다.';renderSwitcher();renderStatus();renderGoals();renderRanking();renderLedger();$('#rules').textContent=(S.settings.group_rules||'매주 일요일 자정 정산').split('\n')[0]}
async function toggleCheck(id){const g=S.goals.find(x=>x.id===id),ex=S.checks.find(c=>c.goal_id===id&&c.check_date===ds());try{if(ex){if(g.cadence==='weekly'){toast('오늘은 이미 기록했어요');return}await api(`goal_checkins?id=eq.${ex.id}`,{method:'DELETE'});toast('체크를 취소했어요')}else{await api('goal_checkins',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({goal_id:id,check_date:ds(),note:''})});toast('+20 XP')}await load()}catch(e){console.error(e);toast('저장하지 못했어요')}}
function syncCadence(){const weekly=$('#goalCadence').value==='weekly';$('#goalTarget').disabled=!weekly;if(!weekly)$('#goalTarget').value=1}
function openGoal(g=null){$('#goalForm').reset();$('#goalId').value=g?.id||'';$('#dialogTitle').textContent=g?'할 일 수정':'새 할 일';$('#goalTitle').value=g?.title||'';$('#goalDesc').value=g?.description||'';$('#goalProof').value=g?.proof_method||'';$('#goalCadence').value=g?.cadence||'daily';$('#goalTarget').value=g?.target_count||1;$('#goalFine').value=g?.fine_amount??10000;$('#deleteGoal').hidden=!g;syncCadence();$('#goalDialog').showModal()}
async function saveGoal(e){e.preventDefault();const id=$('#goalId').value,p={member_id:S.memberId,title:$('#goalTitle').value.trim(),description:$('#goalDesc').value.trim(),proof_method:$('#goalProof').value.trim(),cadence:$('#goalCadence').value,target_count:Number($('#goalTarget').value)||1,fine_amount:Number($('#goalFine').value)||0,active:true};if(!p.title)return;try{await api(id?`goals?id=eq.${id}`:'goals',{method:id?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(p)});$('#goalDialog').close();toast(id?'수정했어요':'추가했어요');await load()}catch(e2){console.error(e2);toast('저장하지 못했어요')}}
async function deleteGoal(){const id=$('#goalId').value;if(!id||!confirm('이 할 일을 종료할까요? 과거 체크와 벌금 기록은 남습니다.'))return;try{await api(`goals?id=eq.${id}`,{method:'DELETE'});$('#goalDialog').close();toast('종료했어요');await load()}catch(e){console.error(e);toast('처리하지 못했어요')}}
async function settle(id){if(!confirm('정산 완료로 표시할까요? 원장 금액은 그대로 남습니다.'))return;try{await api(`fine_ledger?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'settled'})});toast('정산 완료');await load()}catch(e){console.error(e);toast('처리하지 못했어요')}}
async function backup(){const payload={exported_at:new Date().toISOString(),organization:'ILSHINHOE',members:S.members,goals:S.goals,goal_checkins:S.checks,fine_ledger:S.ledger,settings:S.settings};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ilshinhoe-backup-${ds()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('백업 파일을 만들었어요')}
async function badge(){if(!('setAppBadge' in navigator))return;const n=memberGoals(S.memberId).filter(g=>g.cadence==='daily'&&!todayDone(g)).length;try{n?await navigator.setAppBadge(n):await navigator.clearAppBadge()}catch{}}
async function load(){const sync=$('#sync');sync.className='sync';try{const start=ds(addDays(new Date(),-365));const [members,goals,checks,settings,quotes,ledger]=await Promise.all([api('members?select=*&order=created_at.asc'),api('goals?select=*&order=sort_order.asc,created_at.asc'),api(`goal_checkins?select=*&check_date=gte.${start}&order=check_date.desc`),api('settings?select=*'),api('quotes?select=*&active=eq.true&order=id.asc'),api('fine_ledger?select=*&order=week_start.desc,created_at.desc')]);S.members=members||[];S.goals=goals||[];S.checks=checks||[];S.quotes=quotes||[];S.ledger=ledger||[];S.settings=Object.fromEntries((settings||[]).map(x=>[x.key,x.value]));if(!member(S.memberId)&&S.members[0])chooseMember(S.members[0].id);else render();sync.classList.add('ok');badge()}catch(e){console.error(e);sync.classList.add('bad');toast('서버 연결을 확인해주세요')}}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${b.dataset.view}`));window.scrollTo({top:0,behavior:'smooth'})});
$('#addGoal').onclick=()=>openGoal();$('#goalCadence').onchange=syncCadence;$('#goalForm').addEventListener('submit',saveGoal);$('#deleteGoal').onclick=deleteGoal;$('#backup').onclick=backup;
let promptEvent=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(promptEvent){promptEvent.prompt();await promptEvent.userChoice;promptEvent=null;$('#install').hidden=true}else toast('Chrome 메뉴에서 앱 설치를 선택해주세요')};window.addEventListener('appinstalled',()=>{$('#install').hidden=true;toast('일신회 앱 설치 완료')});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=11').catch(console.error));
load();setInterval(load,60000);